### ISSUE TITLE
Is there anyway to make this an action that occurs with every `docker-compose down`?

### ISSUE THREAD

**Issue by Lazalatin** [PepeCitron/vintagestory-server#3]
Is there anyway to make this an action that occurs with every `docker-compose down`?

_Originally posted by @caramelpony in https://github.com/PepeCitron/vintagestory-server/issues/2#issuecomment-2488353861_

I think we should address this in a separate issue.
I looked at the general structure of the Dockerfile and the behaviour can be mitigated by dividing the server files from the world files in two separate folders and providing a volume mount for the server files while still providing the bind mount for the world files.

I will provide a suggesting PR, but it will take some time for testing. If @PepeCitron has any objections or hints, they are much appreciated :)

**Comment by PepeCitron** [comment]
I don't think it's possible to run an action for every `docker-compose down`.

I think I've found the problem. I'm preparing a PR #5 and doing some tests in the evening.

**Comment by PepeCitron** [comment]
The problem mentioned in #2 came from the fact that during a `docker-compose down` the server DLL files were not kept, because inside the container they are in `/data`. As the container has a volume on `/data/server-file` which means that during a `docker-compose down` the DLLs are not kept.

So I modified the server download condition so that it is done in case of update via `SERVER_VERSION` or if the DLLs are absent.
